/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTenantInputBody,
  ErrorModel,
  ListTenantsParams,
  TenantResponse,
  TransitionInputBody
} from '../model';

import { customInstance } from '../../lib/axios';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;





/**
 * @summary List tenants
 */
export const listTenants = (
    params?: ListTenantsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TenantResponse[] | null>(
      {url: `/api/v1/tenants`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListTenantsQueryKey = (params?: ListTenantsParams,) => {
    return [
    `/api/v1/tenants`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListTenantsQueryOptions = <TData = Awaited<ReturnType<typeof listTenants>>, TError = ErrorModel>(params?: ListTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTenants>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTenantsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTenants>>> = ({ signal }) => listTenants(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTenants>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTenantsQueryResult = NonNullable<Awaited<ReturnType<typeof listTenants>>>
export type ListTenantsQueryError = ErrorModel


export function useListTenants<TData = Awaited<ReturnType<typeof listTenants>>, TError = ErrorModel>(
 params: undefined |  ListTenantsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTenants>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTenants>>,
          TError,
          Awaited<ReturnType<typeof listTenants>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTenants<TData = Awaited<ReturnType<typeof listTenants>>, TError = ErrorModel>(
 params?: ListTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTenants>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTenants>>,
          TError,
          Awaited<ReturnType<typeof listTenants>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTenants<TData = Awaited<ReturnType<typeof listTenants>>, TError = ErrorModel>(
 params?: ListTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTenants>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List tenants
 */

export function useListTenants<TData = Awaited<ReturnType<typeof listTenants>>, TError = ErrorModel>(
 params?: ListTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTenants>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTenantsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a new tenant
 */
export const createTenant = (
    createTenantInputBody: NonReadonly<CreateTenantInputBody>,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TenantResponse>(
      {url: `/api/v1/tenants`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTenantInputBody, signal
    },
      );
    }
  


export const getCreateTenantMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTenant>>, TError,{data: NonReadonly<CreateTenantInputBody>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTenant>>, TError,{data: NonReadonly<CreateTenantInputBody>}, TContext> => {

const mutationKey = ['createTenant'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTenant>>, {data: NonReadonly<CreateTenantInputBody>}> = (props) => {
          const {data} = props ?? {};

          return  createTenant(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTenantMutationResult = NonNullable<Awaited<ReturnType<typeof createTenant>>>
    export type CreateTenantMutationBody = NonReadonly<CreateTenantInputBody>
    export type CreateTenantMutationError = ErrorModel

    /**
 * @summary Create a new tenant
 */
export const useCreateTenant = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTenant>>, TError,{data: NonReadonly<CreateTenantInputBody>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTenant>>,
        TError,
        {data: NonReadonly<CreateTenantInputBody>},
        TContext
      > => {
      return useMutation(getCreateTenantMutationOptions(options), queryClient);
    }
    /**
 * @summary Get a tenant by ID
 */
export const getTenant = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TenantResponse>(
      {url: `/api/v1/tenants/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetTenantQueryKey = (id: string,) => {
    return [
    `/api/v1/tenants/${id}`
    ] as const;
    }

    
export const getGetTenantQueryOptions = <TData = Awaited<ReturnType<typeof getTenant>>, TError = ErrorModel>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenant>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTenantQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTenant>>> = ({ signal }) => getTenant(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTenant>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTenantQueryResult = NonNullable<Awaited<ReturnType<typeof getTenant>>>
export type GetTenantQueryError = ErrorModel


export function useGetTenant<TData = Awaited<ReturnType<typeof getTenant>>, TError = ErrorModel>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenant>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTenant>>,
          TError,
          Awaited<ReturnType<typeof getTenant>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTenant<TData = Awaited<ReturnType<typeof getTenant>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenant>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTenant>>,
          TError,
          Awaited<ReturnType<typeof getTenant>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTenant<TData = Awaited<ReturnType<typeof getTenant>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenant>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a tenant by ID
 */

export function useGetTenant<TData = Awaited<ReturnType<typeof getTenant>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenant>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTenantQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Trigger a lifecycle event
 */
export const transitionTenant = (
    id: string,
    transitionInputBody: NonReadonly<TransitionInputBody>,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TenantResponse>(
      {url: `/api/v1/tenants/${id}/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: transitionInputBody, signal
    },
      );
    }
  


export const getTransitionTenantMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transitionTenant>>, TError,{id: string;data: NonReadonly<TransitionInputBody>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof transitionTenant>>, TError,{id: string;data: NonReadonly<TransitionInputBody>}, TContext> => {

const mutationKey = ['transitionTenant'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof transitionTenant>>, {id: string;data: NonReadonly<TransitionInputBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  transitionTenant(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type TransitionTenantMutationResult = NonNullable<Awaited<ReturnType<typeof transitionTenant>>>
    export type TransitionTenantMutationBody = NonReadonly<TransitionInputBody>
    export type TransitionTenantMutationError = ErrorModel

    /**
 * @summary Trigger a lifecycle event
 */
export const useTransitionTenant = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof transitionTenant>>, TError,{id: string;data: NonReadonly<TransitionInputBody>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof transitionTenant>>,
        TError,
        {id: string;data: NonReadonly<TransitionInputBody>},
        TContext
      > => {
      return useMutation(getTransitionTenantMutationOptions(options), queryClient);
    }
    