/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List tenants
 */
export const listTenantsQueryLimitDefault = 50;
export const listTenantsQueryOffsetDefault = 0;

export const ListTenantsQueryParams = zod.object({
  "status": zod.string().optional().describe('Filter by status'),
  "limit": zod.number().default(listTenantsQueryLimitDefault).describe('Max results'),
  "offset": zod.number().default(listTenantsQueryOffsetDefault).describe('Pagination offset')
})

export const ListTenantsResponseItem = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.string().describe('Creation timestamp (ISO 8601)'),
  "id": zod.string().describe('Unique identifier'),
  "name": zod.string().describe('Display name'),
  "plan": zod.string().describe('Subscription plan'),
  "slug": zod.string().describe('URL-friendly identifier'),
  "status": zod.string().describe('Lifecycle state'),
  "updated_at": zod.string().describe('Last update timestamp (ISO 8601)')
})
export const ListTenantsResponse = zod.array(ListTenantsResponseItem)

/**
 * @summary Create a new tenant
 */
export const createTenantBodyNameMax = 255;

export const createTenantBodyPlanDefault = `free`;
export const createTenantBodySlugMax = 100;


export const createTenantBodySlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)\*$');


export const CreateTenantBody = zod.object({
  "name": zod.string().min(1).max(createTenantBodyNameMax).describe('Display name'),
  "plan": zod.string().default(createTenantBodyPlanDefault).describe('Subscription plan'),
  "slug": zod.string().min(1).max(createTenantBodySlugMax).regex(createTenantBodySlugRegExp).describe('URL-friendly identifier (lowercase, hyphens)')
})

export const CreateTenantResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.string().describe('Creation timestamp (ISO 8601)'),
  "id": zod.string().describe('Unique identifier'),
  "name": zod.string().describe('Display name'),
  "plan": zod.string().describe('Subscription plan'),
  "slug": zod.string().describe('URL-friendly identifier'),
  "status": zod.string().describe('Lifecycle state'),
  "updated_at": zod.string().describe('Last update timestamp (ISO 8601)')
})

/**
 * @summary Get a tenant by ID
 */
export const GetTenantParams = zod.object({
  "id": zod.string().describe('Tenant ID')
})

export const GetTenantResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.string().describe('Creation timestamp (ISO 8601)'),
  "id": zod.string().describe('Unique identifier'),
  "name": zod.string().describe('Display name'),
  "plan": zod.string().describe('Subscription plan'),
  "slug": zod.string().describe('URL-friendly identifier'),
  "status": zod.string().describe('Lifecycle state'),
  "updated_at": zod.string().describe('Last update timestamp (ISO 8601)')
})

/**
 * @summary Trigger a lifecycle event
 */
export const TransitionTenantParams = zod.object({
  "id": zod.string().describe('Tenant ID')
})

export const TransitionTenantBody = zod.object({
  "event": zod.enum(['provision_complete', 'suspend', 'reactivate', 'delete', 'deletion_complete']).describe('Lifecycle event to trigger')
})

export const TransitionTenantResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.string().describe('Creation timestamp (ISO 8601)'),
  "id": zod.string().describe('Unique identifier'),
  "name": zod.string().describe('Display name'),
  "plan": zod.string().describe('Subscription plan'),
  "slug": zod.string().describe('URL-friendly identifier'),
  "status": zod.string().describe('Lifecycle state'),
  "updated_at": zod.string().describe('Last update timestamp (ISO 8601)')
})

