/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */
import type { CreateUserInputBodyRole } from './createUserInputBodyRole';

export interface CreateUserInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Email address */
  email: string;
  /**
   * Display name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * Password (min 8 chars)
   * @minLength 8
   * @maxLength 128
   */
  password: string;
  /** User role */
  role: CreateUserInputBodyRole;
}
