/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */

export interface CreateTenantInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Display name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** Subscription plan */
  plan?: string;
  /**
   * URL-friendly identifier (lowercase, hyphens)
   * @minLength 1
   * @maxLength 100
   * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
   */
  slug: string;
}
