/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */

export type ListTenantsParams = {
/**
 * Filter by status
 */
status?: string;
/**
 * Max results
 */
limit?: number;
/**
 * Pagination offset
 */
offset?: number;
};
