/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */

export interface MeOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Authenticated user email */
  email: string;
  /** Authenticated user role */
  role: string;
  /** Authenticated user ID */
  user_id: string;
}
