/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */

export interface RefreshInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Refresh token
   * @minLength 1
   */
  refresh_token: string;
}
