/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */
import type { TransitionInputBodyEvent } from './transitionInputBodyEvent';

export interface TransitionInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Lifecycle event to trigger */
  event: TransitionInputBodyEvent;
}
