/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */

/**
 * Lifecycle event to trigger
 */
export type TransitionInputBodyEvent = typeof TransitionInputBodyEvent[keyof typeof TransitionInputBodyEvent];


export const TransitionInputBodyEvent = {
  provision_complete: 'provision_complete',
  suspend: 'suspend',
  reactivate: 'reactivate',
  delete: 'delete',
  deletion_complete: 'deletion_complete',
} as const;
