/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */

export interface UpdatePasswordInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Current password
   * @minLength 1
   */
  current_password: string;
  /**
   * New password (min 8 chars)
   * @minLength 8
   * @maxLength 128
   */
  new_password: string;
}
