/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateUserInputBodyRole } from './updateUserInputBodyRole';

export interface UpdateUserInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Display name
   * @maxLength 255
   */
  name?: string;
  /** User role */
  role?: UpdateUserInputBodyRole;
}
