/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */

/**
 * User role
 */
export type UpdateUserInputBodyRole = typeof UpdateUserInputBodyRole[keyof typeof UpdateUserInputBodyRole];


export const UpdateUserInputBodyRole = {
  superadmin: 'superadmin',
  admin: 'admin',
  viewer: 'viewer',
} as const;
