/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */

export interface UserResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Creation timestamp (ISO 8601) */
  created_at: string;
  /** Email address */
  email: string;
  /** Unique identifier */
  id: string;
  /** Display name */
  name: string;
  /** User role (superadmin, admin, viewer) */
  role: string;
  /** Last update timestamp (ISO 8601) */
  updated_at: string;
}
