/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List all users
 */
export const ListUsersResponseItem = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.string().describe('Creation timestamp (ISO 8601)'),
  "email": zod.string().describe('Email address'),
  "id": zod.string().describe('Unique identifier'),
  "name": zod.string().describe('Display name'),
  "role": zod.string().describe('User role (superadmin, admin, viewer)'),
  "updated_at": zod.string().describe('Last update timestamp (ISO 8601)')
})
export const ListUsersResponse = zod.array(ListUsersResponseItem)

/**
 * @summary Create a new user
 */
export const createUserBodyNameMax = 255;

export const createUserBodyPasswordMin = 8;
export const createUserBodyPasswordMax = 128;



export const CreateUserBody = zod.object({
  "email": zod.email().describe('Email address'),
  "name": zod.string().min(1).max(createUserBodyNameMax).describe('Display name'),
  "password": zod.string().min(createUserBodyPasswordMin).max(createUserBodyPasswordMax).describe('Password (min 8 chars)'),
  "role": zod.enum(['superadmin', 'admin', 'viewer']).describe('User role')
})

export const CreateUserResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.string().describe('Creation timestamp (ISO 8601)'),
  "email": zod.string().describe('Email address'),
  "id": zod.string().describe('Unique identifier'),
  "name": zod.string().describe('Display name'),
  "role": zod.string().describe('User role (superadmin, admin, viewer)'),
  "updated_at": zod.string().describe('Last update timestamp (ISO 8601)')
})

/**
 * @summary Delete a user
 */
export const DeleteUserParams = zod.object({
  "id": zod.string().describe('User ID')
})

/**
 * @summary Get a user by ID
 */
export const GetUserParams = zod.object({
  "id": zod.string().describe('User ID')
})

export const GetUserResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.string().describe('Creation timestamp (ISO 8601)'),
  "email": zod.string().describe('Email address'),
  "id": zod.string().describe('Unique identifier'),
  "name": zod.string().describe('Display name'),
  "role": zod.string().describe('User role (superadmin, admin, viewer)'),
  "updated_at": zod.string().describe('Last update timestamp (ISO 8601)')
})

/**
 * @summary Update a user's name or role
 */
export const UpdateUserParams = zod.object({
  "id": zod.string().describe('User ID')
})

export const updateUserBodyNameMax = 255;



export const UpdateUserBody = zod.object({
  "name": zod.string().max(updateUserBodyNameMax).optional().describe('Display name'),
  "role": zod.enum(['superadmin', 'admin', 'viewer']).optional().describe('User role')
})

export const UpdateUserResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.string().describe('Creation timestamp (ISO 8601)'),
  "email": zod.string().describe('Email address'),
  "id": zod.string().describe('Unique identifier'),
  "name": zod.string().describe('Display name'),
  "role": zod.string().describe('User role (superadmin, admin, viewer)'),
  "updated_at": zod.string().describe('Last update timestamp (ISO 8601)')
})

/**
 * @summary Update own password
 */
export const UpdatePasswordParams = zod.object({
  "id": zod.string().describe('User ID')
})


export const updatePasswordBodyNewPasswordMin = 8;
export const updatePasswordBodyNewPasswordMax = 128;



export const UpdatePasswordBody = zod.object({
  "current_password": zod.string().min(1).describe('Current password'),
  "new_password": zod.string().min(updatePasswordBodyNewPasswordMin).max(updatePasswordBodyNewPasswordMax).describe('New password (min 8 chars)')
})

