/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * tenantiq
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Authenticate with email and password
 */



export const LoginBody = zod.object({
  "email": zod.email().describe('User email'),
  "password": zod.string().min(1).describe('User password')
})

export const LoginResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "AccessToken": zod.string(),
  "RefreshToken": zod.string()
})

/**
 * @summary Get the current authenticated user
 */
export const MeResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "email": zod.string().describe('Authenticated user email'),
  "role": zod.string().describe('Authenticated user role'),
  "user_id": zod.string().describe('Authenticated user ID')
})

/**
 * @summary Refresh an access token
 */
export const RefreshTokenBody = zod.object({
  "refresh_token": zod.string().optional().describe('Refresh token (optional when using cookies)')
})

export const RefreshTokenResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "AccessToken": zod.string(),
  "RefreshToken": zod.string()
})

